Controllers/CustomersController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using stationary_shop.Repositories;
using stationary_shop.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace stationary_shop.Controllers
{
    public class CustomersController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(CustomersRepo.List());
        }

        [HttpGet]
        public ActionResult Create()
        {
            var customer = new Customers();
            return View(customer);
        }


        [HttpPost]
        public ActionResult Create(Customers customer)
        {
            if(ModelState.IsValid)
            {
                CustomersRepo.Insert(customer);

                return RedirectToAction("Index");
            }
            return View(customer);
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            var customer = CustomersRepo.Find(id);
            return View(customer);
        }
        [HttpPost]
        public ActionResult Edit(string id, Customers customer)
        {
           // if(ModelState.IsValid)
           // {
                CustomersRepo.Update(customer);

                return RedirectToAction("Index");
            //}
            //return View(customer);
        }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            var customer = CustomersRepo.Find(id);
            return View(customer);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(string id)
        {
            try
            {
                CustomersRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch( MySql.Data.MySqlClient.MySqlException)
            {
                ViewData["deletionNotPermitted"] = true;

                var customer = CustomersRepo.Find(id);       
                return View("Delete", customer);
            }
        }
    }
}

Controllers/OrdersController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using stationary_shop.Repositories;
using stationary_shop.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace stationary_shop.Controllers
{
    public class OrdersController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(OrdersRepo.List());
        }

        [HttpGet]
        public ActionResult Create()
        {
            var order = new Orders();
            //PopulateSelections(narys);
            return View(order);
        }


        [HttpPost]
        public ActionResult Create(Orders order)
        {
           

            if(ModelState.IsValid)
            {
                OrdersRepo.Insert(order);

                return RedirectToAction("Index");
            }
            //PopulateSelections(narys);
            return View(order);
        }

        // [HttpPost]
        // public ActionResult Edit(string id, Narys narys)
        // {
        //     if(ModelState.IsValid)
        //     {
        //         OrdersRepo.Update(narys);

        //         return RedirectToAction("Index");
        //     }
        //     PopulateSelections(narys);
        //     return View(narys);
        // }

        // [HttpGet]
        // public ActionResult Edit(string id)
        // {
        //     var narys = OrdersRepo.Find(id);
        //     PopulateSelections(narys);

        //     return View(narys);
        // }

        [HttpGet]
        public ActionResult Delete(string id)
        {
            var order = OrdersRepo.Find(id);
            return View(order);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(string id)
        {
            try
            {
                OrdersRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch( MySql.Data.MySqlClient.MySqlException)
            {
                ViewData["deletionNotPermitted"] = true;

                var order = OrdersRepo.Find(id);
                //PopulateSelections(narys);
                
                return View("Delete", order);
            }
        }

        // public void PopulateSelections(Narys narys)
        // {
        //     var lytys = OrdersRepo.ListLytis();

        //     narys.Lists.Lytys =
        //         lytys.Select(it => {
        //             return
        //                 new SelectListItem(){
        //                     Value = Convert.ToString(it.ID),
        //                     Text = it.Name
        //                 };
        //         }).ToList();
        // }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using stationary_shop.Repositories;
using Microsoft.AspNetCore.Mvc;
using stationary_shop.Models;

namespace stationary_shop.Controllers
{
    public class ProductsController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View(ProductsRepo.List());
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            var product = ProductsRepo.Find(id);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(string id, Products product)
        {
           if(ModelState.IsValid)
           {
                ProductsRepo.Update(product);

                return RedirectToAction("Index");
            }
            return View(product);
        }
        [HttpGet]
        public ActionResult Create()
        {
            var product = new Products();
            return View(product);
        }


        [HttpPost]
        public ActionResult Create(Products product)
        {
            if(ModelState.IsValid)
            {
                ProductsRepo.Insert(product);

                return RedirectToAction("Index");
            }
            return View(product);
        }

        [HttpPost]
        public ActionResult DeleteConfirm(string id)
        {
            try
            {
                ProductsRepo.Delete(id);

                return RedirectToAction("Index");
            }
            catch( MySql.Data.MySqlClient.MySqlException)
            {
                ViewData["deletionNotPermitted"] = true;

                var customer = ProductsRepo.Find(id);       
                return View("Delete", customer);
            }
        }
        
        [HttpGet]
        public ActionResult Delete(string id)
        {
            var customer = ProductsRepo.Find(id);
            return View(customer);
        }
    }
}

Views/_Layout.cshtml
@{
	/// <summary>
	/// Helper for marking active links in main menu.
	/// </summary>
	/// <param name="ctrl">Controller to look for.</param>
	/// <param name="act">Action to look for. Pass null if action does not matter.</param>
	/// <returns>If controller and (optionally) action match given ones returns "active". Returns empty string otherwise.</returns>
	string MarkActive(string ctrl, string act = null)
	{
		//get current controller and action
		var curCtrl = (string)ViewContext.RouteData.Values["Controller"];
		var curAct = (string)ViewContext.RouteData.Values["Action"];

		//compare to given ones
		if( curCtrl == ctrl && (act == null || curAct == act) )
			return "active";
		return "";
	}
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	@* ViewData["title"] gets set in view templates *@
	<title>Stationary - @ViewData["title"]</title>

	<!-- this contains core scripts and styles and is built by webpack -->
	<script src="@Url.Content("~/deps/dist/main.js")"></script>

	<!-- you can use these to add your own scripts and styles quickly -->
	<script src="@Url.Content("~/deps-manual/index.js")"></script>
	<link href="@Url.Content("~/deps-manual/style.css")" rel="stylesheet"/>
	
	<script>
	//<![CDATA[
		//pull in top most jQuery function exposed from module built by webpack; for use in jQuery plug-in initialization code
		var $ = window.__jQuery;
	//]]>
	</script>
</head>
<body>
	<div class="page-container">
		@* page header, also main menu *@
		<nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
			<div class="container-fluid">
				@* home button *@
				<a class="navbar-brand" href="@Url.Action("Index", "Home")" class="navbar-brand"><i class="fa-solid fa-car"></i></a>

				@* this buttons shows drop down menu on narrow screens; it is invisible normally *@
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarContent"
				>
					<span class="navbar-toggler-icon"></span>
				</button>

				@* menu links for forms and reports *@
				<div class="container-fluid d-flex justify-content-center">
					<div class="collapse navbar-collapse" id="navbarContent">
						<ul class="navbar-nav me-auto mb-2 mb-lg-0">
							@* main menu links go here *@
							<li class="nav-item">
								<a href="@Url.Action("Index", "Orders")" class="@MarkActive("Orders") nav-link">Orders</a>
							</li>
							<li class="nav-item"></li>
								<a href="@Url.Action("Index", "Customers")" class="@MarkActive("Customers") nav-link">Customers</a>
							</li>
							<li class="nav-item"></li>
								<a href="@Url.Action("Index", "Products")" class="@MarkActive("Products") nav-link">Products</a>
							</li>
						</ul>

						@* drop-down menu for report links *@
						<ul class="navbar-nav justify-content-right mb-2 mb-lg-0">
							<li class="nav-item dropdown">
								<a
									class="@MarkActive("Report") nav-link dropdown-toggle"
									href="#"
									id="navbarReports"
									role="button"
									data-bs-toggle="dropdown"
									aria-expanded="false"
								>
									Reports
								</a>
								<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarReports">
									@* report links go here *@
									<li>
										<a
											href="@Url.Action("Services", "Reports")"
											class="@MarkActive("Reports", "Services") dropdown-item"
										>Report 1</a>
									</li>
									<li>
										<a
											href="@Url.Action("Contracts", "Reports")"
											class="@MarkActive("Reports", "Contracts") dropdown-item"
										>Report 2</a>
									</li>
									<li>
										<a
											href="@Url.Action("LateContracts", "Reports")"
											class="@MarkActive("Reports", "LateContracts") dropdown-item"
										>Report 3</a>
									</li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>

		@* main content gets rendered here *@
		<div class="main-content">
			@RenderBody()
		</div>

		@* page footer *@
		<div class="page-footer">
			<footer>
				<p>&copy; KTU Informacijos Sistemų Katedra</p>
			</footer>
		</div>
	</div>
	
	@* any JavaScript code comming from script sections in views gets rendered here *@
	@RenderSection("scripts", required: false)

	@* JavaScript code initialization routines go here *@
	<script>
	//<![CDATA[
		//this function gets invoked by the browser when HTML page is fully loaded
		$(document).ready(function () {
			//apply jQuery datatables plugin on tables having CSS class 'entity-list'
			$(".entity-list").DataTable({
				"autoWidth": true,
				language : {
					"decimal":        "",
					"emptyTable":     "no entries",
					"info":           "Entries _START_ to _END_ from _TOTAL_",
					"infoEmpty":      "0",
					"infoFiltered":   "(From _MAX_ entries)",
					"infoPostFix":    "",
					"thousands":      ",",
					"lengthMenu":     "Page: _MENU_",
					"loadingRecords": "Uploading data...",
					"processing":     "Proccesing data...",
					"search":         "Search:",
					"zeroRecords":    "No entries found",
					"paginate": {
						"first":      "First",
						"last":       "Last",
						"next":       "Next",
						"previous":   "Previous"
					},
					"aria": {
						"sortAscending":  ": sort by biggest",
						"sortDescending": ": sort by smallest"
					}
				}
			});

			//apply jQuery datetimepicker plugin on fields having CSS classes 'date-picker' and 'datetime-picker'
			$(".date-picker").datetimepicker({ timepicker:false, format: 'Y-m-d' });
			$(".datetime-picker").datetimepicker({ format: 'Y-m-d h:i' });
		});
	//]]>
	</script>
</body>
</html>